dropweapon_menu_cl_autoswitch=Авто-переключение на подобранное оружие
dropweapon_menu_sv_blacklist=Чёрный список
dropweapon_menu_sv_blacklist_adminbypass=Могут ли админы игнорировать чёрный список
dropweapon_menu_sv_ondeath=Выбрасывать оружия после смерти
dropweapon_menu_sv_ondeath_activeonly=Выбрасывать только оружие в руках после смерти
