dropweapon_menu_cl_autoswitch=Auto-switch to picked up weapon
dropweapon_menu_sv_blacklist=Blacklist
dropweapon_menu_sv_blacklist_adminbypass=Admins can bypass blacklist
dropweapon_menu_sv_ondeath=Drop weapons on death
dropweapon_menu_sv_ondeath_activeonly=Drop only active weapon on death
